version: '3'

services:

  filebeat:
    build: filebeat/

    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    volumes: ['/var/log:/mnt/log:ro', './filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml']
